### ISSUE TITLE
我只想选择文件

### ISSUE THREAD

**Issue by lishangwl** [zippo88888888/ZFileManager#10]
看了半天文档，和试了各种命令。我还是没找到怎么只选文件。

**Comment by zippo88888888** [comment]
ZFileConfiguration --> needLongClick = false

**Comment by LEEVISIT** [comment]
> ZFileConfiguration --> needLongClick = false

这样设置没用.
我是下面这种做法:

MyFileTypeListener类中  override fun getFileType(filePath: String) = MyTxtType(), 同时重写MyTxtType类中openFile()就可以了.

**Comment by zippo88888888** [comment]
原来你只是不需要点击自动打开文件...    如果想所有文件都这样操作，继承 ZFileOpenListener，重写方法就可以！

**Comment by zippo88888888** [comment]
原来你只是不需要点击自动打开文件...    如果想所有文件都这样操作，继承 ZFileOpenListener，重写方法就可以！

**Comment by lishangwl** [comment]
暂时没用这个库了。感谢大佬的库。

**Comment by LEEVISIT** [comment]
这个库还是蛮好的,别的库很多文件加载不出来,android 11、12各种兼容性问题

**Comment by lishangwl** [comment]
> 这个库还是蛮好的,别的库很多文件加载不出来,android 11、12各种兼容性问题

好是听好的。kotlin的写法有点太看不懂。以后回来再用

**Comment by zippo88888888** [comment]
1.4.1 版本已修复
