### ISSUE TITLE
文件大小限制提示

### ISSUE THREAD

**Issue by LEEVISIT** [zippo88888888/ZFileManager#11]
2022-07-15 17:34:35.940 17881-17881/com.zp.zfile_manager E/-----: selete  size:140.7735471725464
2022-07-15 17:34:35.941 17881-17881/com.zp.zfile_manager E/-----: config.maxSize:15
2022-07-15 17:34:35.941 17881-17881/com.zp.zfile_manager E/-----: config.maxSizeStr:您只能选取小于10M的文件

设置了最大为15M,超过15M后提示语仍然为默认的10M

ZFileListAdapter.java  175行

**Comment by LEEVISIT** [comment]
必须要在config中设置,否则就会出现上面的bug
config {
                    getZFileConfig().apply {
                        boxStyle = ZFileConfiguration.STYLE2
                        maxLength = 1
                        maxSize = 15
                        maxSizeStr = "您只能选取小于${maxSize}M的文件"
                        needLongClick = false
                        needTwiceClick = false
                        isOnlyFileHasLongClick = true
                        titleGravity = ZFileConfiguration.TITLE_CENTER
                        maxLengthStr = "老铁最多6个文件"
                        authority = Content.AUTHORITY
                    }

**Comment by zippo88888888** [comment]
好的，感谢反馈！[笔芯]

**Comment by zippo88888888** [comment]
1.4.1已修复
