### ISSUE TITLE
相关zip代码上架谷歌商店爆警告

### ISSUE THREAD

**Issue by Jun19** [zippo88888888/ZFileManager#12]
大概内容是：您的应用存在不安全的解压缩模式，可能会导致路径遍历安全漏洞。
https://support.google.com/faqs/answer/9294009

**Comment by zippo88888888** [comment]
感谢反馈[笔芯]

**Comment by Jun19** [comment]
您好 请问最近有没有更新这个的计划呢

**Comment by Jun19** [comment]
应该在ZFileUtil的extractFile里面解压文件和文件夹的时候判断一下路径就可以了 不过以下代码未经过测试
       if (!file.canonicalPath.startsWith(outPutDir)) {
                        throw SecurityException("Zip Security Exception")
                    }

**Comment by zippo88888888** [comment]
1.4.1版本 版本已新增解压判断
