### ISSUE TITLE
ZFileStipulateAsync 在华为小米手机上筛选文件不返回数据

### ISSUE THREAD

**Issue by TwinterT** [zippo88888888/ZFileManager#15]
使用ContentResolver查询的MediaStore.Files.FileColumns.DATA被废弃了，不会返回数据，是否考虑换成MediaStore.Files.FileColumns._ID转成Uri来支持Android10以上版本？

**Comment by zippo88888888** [comment]
感谢反馈！  后续版本可能（毕竟该功能只是本库的一个小扩展）会进行修改！
无法获取数据：可通过 继承 ZFileStipulateAsync 重写 doingWork 方法 自行实现！使用方式请参考 [SuperActivity](https://github.com/zippo88888888/ZFileManager/blob/master/app/src/main/java/com/zp/zfile_manager/super_/SuperActivity.kt)
