### ISSUE TITLE
android 10以上访问文件建议添加一个 storage access framework

### ISSUE THREAD

**Issue by leonfree888** [zippo88888888/ZFileManager#17]
storage access framework 去读写 android/data/路径下的文件

**Comment by zippo88888888** [comment]
目前支持 开发者 通过继承 [ZFileClickListener](https://github.com/zippo88888888/ZFileManager/blob/master/app/src/main/java/com/zp/zfile_manager/diy/MyFileClickListener.kt) 自行实现 saf！后续会考虑对于 saf的支持，笔芯

**Comment by zippo88888888** [comment]
1.4.6 已支持 SAF
