### ISSUE TITLE
删除文件后，列表的缓存还在。怎么更新，或者怎么调用你的删除

### ISSUE THREAD

**Issue by sy5251** [zippo88888888/ZFileManager#18]
internal object ZFileUtil 无法调用，可以通过什么方法单独调用，或者如果删除文件后怎么刷新缓存，

**Comment by zippo88888888** [comment]
请问 demo 也有这个问题吗？

**Comment by zippo88888888** [comment]
刷新缓存的方法在 [ZFileListFragment](https://github.com/zippo88888888/ZFileManager/blob/master/z_file/src/main/java/com/zp/z_file/ui/ZFileListFragment.kt) 
```kotlin

fun observer(isSuccess: Boolean) {
    if (isSuccess) getData(nowPath)
}

```
通过 FragmentManager.findFragmentByTag 获取 ZFileListFragment 
```kotlin
(supportFragmentManager.findFragmentByTag(getZFileConfig().fragmentTag) as? ZFileListFragment)?.observer(true)
```

**Comment by zippo88888888** [comment]
这边就先关了，有问题再提[笔芯]
