### ISSUE TITLE
微信不能获取图片和视频等等

### ISSUE THREAD

**Issue by gegeName** [zippo88888888/ZFileManager#3]
在这里感谢你的开源的库，经过测试在微信保存视频到本地后的地址为/storage/emulated/0/Download/WeiXin/或者/storage/emulated/0/Pictures/WeiXin/这两个路径都有可能出现。在增加这两个路径显示出了保存的视频或者图片文档，而且检查了你的代码ZFileUtil工具类中的getQWFileData写法有问题，建议优化成为这个样子，就可以增加多个QQ/微信的路径地址
`fun getQWFileData(type: Int, filePathArray: MutableList<String>, filterArray: Array<String>): MutableList<ZFileBean> {
        val list = ArrayList<ZFileBean>()
        val listFiles= mutableListOf<File>()
        if (filePathArray.isNullOrEmpty().not()){
            if (filePathArray.isNotEmpty()){
                filePathArray.forEach {
                    val toFile = it.toFile()
                    if (toFile.exists()){
                        toFile.listFiles(ZFileQWFilter(filterArray,type==ZFILE_QW_OTHER))?.run {
                            listFiles.addAll(this.toList())
                        }
                    }
                }
            }
        }
        listFiles.forEach {
            if (!it.isHidden) {
                val bean = ZFileBean(
                    it.name,
                    it.isFile,
                    it.path,
                    ZFileOtherUtil.getFormatFileDate(it.lastModified()),
                    it.lastModified().toString(),
                    getFileSize(it.length()),
                    it.length()
                )
                list.add(bean)
            }
        }
        if (!list.isNullOrEmpty()) {
            list.sortByDescending { it.originalDate }
        }
        return list
    }`

**Comment by zippo88888888** [comment]
感谢，后续会跟进！ 如果你发现获取微信、QQ有问题，可以自定义的
