### ISSUE TITLE
'kotlin-android-extensions'过时了,

### ISSUE THREAD

**Issue by qssq** [zippo88888888/ZFileManager#9]
我想改,看了下,太多了,而且我一开始就不选择kotlin,证明我是对的,这样好了吧,骚操作自动findbyid呢,我之前就一直用的databind,用了那么多年了还没翻车.

**Comment by qssq** [comment]
我不知道为啥,很多kotlinbinding的问题,不知道是不是extendsion的问题,所以我决定还是弃用这个zfilemanager了,

**Comment by qssq** [comment]
我说的很多问题其实是每一次编译会会报错一次,再次运行方可运行.全是databind问题..

**Comment by zippo88888888** [comment]
说了这么多，你完全可以拿源码自己改动，去掉extendsion 简单配置一下不就好了？你提的那些 说得好像我欠你似的，好像我必须得为你修改一样。本就是开源的，不可能100%符合使用者的需求！再说了，本身项目已高度可自定义了，还BBBB，BNMB，爱用用，不用滚！

**Comment by zippo88888888** [comment]
文件获取 核心方法 

```java
File file = new File(path);
File[] files = file.listFiles(fileFilter);
...
```
非常简单的一个方法，而且还是系统提供的！不符合就自定义或者自己实现，关于你自己项目报错，这是我的问题吗？？？ZFileManager 提供的功能如果说有bug之类的，我会去修改！那么长一篇 白话 使用说明，我是写着好玩的？这个本就是我之前项目的需求，只是这个需求我遇到了不止一次，所以才会封装、开源到GitHub！开源项目不可能100%符合使用者的需求，所以请自便！我最后提一点，kotlin是这世上最好的语言！
